name = "fortran-primes"
version = "0.1.0"
license = "MIT"
author = "Federico Perini"
maintainer = "federico.perini@gmail.com"
copyright = "Copyright 2023, Federico Perini"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
http = { git = "https://github.com/fortran-lang/http-client.git" }
fortran-zlib = { git = "https://github.com/interkosmos/fortran-zlib.git" }
stdlib = "*"
